### ISSUE TITLE
[ndefeditor / pom.xml] dependency webapp-parent missing

### ISSUE THREAD

**Issue by franck-serot** [grundid/ndefeditor#12]
Hi Adrian,
I observed that the file pom.xml of your project "ndefeditor" refers to the parent project "webapp-parent".
Except I'm mistaken, this project "webapp-parent" seems missing from your repository.
I think it is a delivery error.
For the moment, this projet "ndefeditor" can't be compiled because of this dependency.
Could you help me to understand and solve this problem ?
Thank you in advance for your feedback.
Best regards,
Franck

**Comment by JohnMcLear** [comment]
[ERROR]     Non-resolvable parent POM: Could not find artifact de.grundid.maven:webapp-parent:pom:2012.1 in central (http://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 5, column 10 ->

**Comment by grundid** [comment]
Sorry, I missed this issue. 
I just pushed the fix for that.

**Comment by JohnMcLear** [comment]
Thanks!

Should installing using 

```
mvn -am pom.xml
```

work?  Any tips for building from the command line ? :)  Eager to get started doing front end stuff for you

**Comment by JohnMcLear** [comment]
Ah maybe I need to do

```
mvn package
```

first

**Comment by JohnMcLear** [comment]
```
Downloaded: http://repo.maven.apache.org/maven2/org/nfctools/nfctools-ndef/1.0-M6/nfctools-ndef-1.0-M6.jar (120 KB at 9.3 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:10.325s
[INFO] Finished at: Fri May 03 10:07:22 BST 2013
[INFO] Final Memory: 5M/52M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ndefeditor: Could not resolve dependencies for project de.grundid:ndefeditor:war:1.0-SNAPSHOT: Could not find artifact org.nfctools:nfctools-applet:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
jose@jose-S3100 ~/ndefeditor $ git pull
Already up-to-date.
```

Sorry if I'm doing something wrong, I'm completely new to building with maven ;\

**Comment by grundid** [comment]
I'm sorry. I assumed you would have the nfctools-applet installed locally. 

I think, the best way to go on will be to remove the nfctools-applet dependency for the moment. 
I'll move the code and push the changes today.

**Comment by grundid** [comment]
Ok, the changes are online. 
You should be able to build the project with:

mvn package

**Comment by JohnMcLear** [comment]
Looks good :)

```
[INFO] Packaging webapp
[INFO] Assembling webapp [ndefeditor] in [/home/jose/ndefeditor/target/ndefeditor]
[INFO] Processing war project
[INFO] Copying webapp resources [/home/jose/ndefeditor/src/main/webapp]
[INFO] Webapp assembled in [183 msecs]
[INFO] Building war: /home/jose/ndefeditor/target/ndefeditor.war
[INFO] WEB-INF/web.xml already added, skipping
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:19.790s
[INFO] Finished at: Fri May 03 10:42:11 BST 2013
[INFO] Final Memory: 16M/60M
[INFO] ------------------------------------------------------------------------
```

**Comment by JohnMcLear** [comment]
Final question, any preference on the webserver to provide the .war file?  I was going to follow this guide
https://blogs.oracle.com/chengfang/entry/how_to_run_a_war

**Comment by grundid** [comment]
I'm using Tomcat (http://tomcat.apache.org/) for that

**Comment by JohnMcLear** [comment]
Attempting to use https://wiki.base22.com/display/btg/How+to+create+a+Maven+web+app+and+deploy+to+Tomcat+-+fast#HowtocreateaMavenwebappanddeploytoTomcat-fast-StepOne-PreparetheTomcatManagerapplication

**Comment by JohnMcLear** [comment]
Any idea what I'm doing wrong?

```
jose-S3100 ndefeditor # mvn tomcat:deploy
...
[INFO] 
[INFO] --- maven-war-plugin:2.1.1:war (default-war) @ ndefeditor ---
[INFO] Packaging webapp
[INFO] Assembling webapp [ndefeditor] in [/home/jose/ndefeditor/target/ndefeditor]
[INFO] Processing war project
[INFO] Copying webapp resources [/home/jose/ndefeditor/src/main/webapp]
[INFO] Webapp assembled in [291 msecs]
[INFO] Building war: /home/jose/ndefeditor/target/ndefeditor.war
[INFO] WEB-INF/web.xml already added, skipping
[INFO] 
[INFO] <<< tomcat-maven-plugin:1.1:deploy (default-cli) @ ndefeditor <<<
[INFO] 
[INFO] --- tomcat-maven-plugin:1.1:deploy (default-cli) @ ndefeditor ---
[INFO] Deploying war to http://localhost:8080/ndefeditor  
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.528s
[INFO] Finished at: Sat May 04 22:03:20 BST 2013
[INFO] Final Memory: 11M/133M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:tomcat-maven-plugin:1.1:deploy (default-cli) on project ndefeditor: Cannot invoke Tomcat manager: Server returned HTTP response code: 401 for URL: http://localhost:8080/manager/deploy?path=%2Fndefeditor&war= -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException


```

**Comment by grundid** [comment]
I assume you are trying to deploy the war file to your tomcat instance.

The 401 error means your deploy plugin is not authorized to access the tomcat manager. You can define your user/pass info in the pom.xml or your settings.xml file.

However I would not recommend to constantly redeploy the war file during development. What IDE do you use?
If you have Eclipse you can launch Tomcat from Eclipse and it will constantly republish all changes to Tomcat.
I'm using STS (http://www.springsource.org/sts) as this Eclipse package has all the plugins that I need.

**Comment by JohnMcLear** [comment]
Ah, me and Java don't get on ;)  I don't use any IDE, I will see where I get to by defining my user/pass in the pom.xml or settings.xml

**Comment by JohnMcLear** [comment]
Btw the 401 URL is 

```
 http://localhost:8080/manager/deploy?path=%2Fndefeditor&war= -
```

note that no war parameter is included, is this expected?
