### ISSUE TITLE
Adopt a real license

### ISSUE THREAD

**Issue by JohnMcLear** [grundid/ndefeditor#3]
I'd suggest the Apache2 license as it will give people the most amount of confidence when contributing to the project.

**Comment by JohnMcLear** [comment]
Also the license file should just be called LICENSE .txt is superfluous

**Comment by JohnMcLear** [comment]
Oh and I noticed the Affero license is in there..  The Affero license is a bit extremist in the GNU world..  "if you run the program on a server and let other users communicate with it there, your server must also allow them to download the source code corresponding to the program that it's running."

See... http://3.bp.blogspot.com/--EfX5P6Ny7Q/T6aSO_LdpNI/AAAAAAAAAgY/v-QFMmbP5As/s1600/OSS+License.png

**Comment by grundid** [comment]
The ndefeditor is an online tool. The Affero GPL is a perfect choice here.

**Comment by JohnMcLear** [comment]
Okay as long as you are aware of that clause, it's fine with me but others may question this in the future.
