### ISSUE TITLE
The WebApp depends on Spring but I don't see why.

### ISSUE THREAD

**Issue by JohnMcLear** [grundid/ndefeditor#9]
What am I missing here?  Spring is a huge dependency for such a small app that is 99% HTML/CSS/JS

I'm assuming I'm missing the QRCode generator or something that runs locally?

**Comment by JohnMcLear** [comment]
Any chance of a comment on this please?

**Comment by grundid** [comment]
I thought it is duplicate of #10

**Comment by JohnMcLear** [comment]
Oh, so I was right in assuming Java is only used for creating the QR code?  I kinda thought I was missing something..  How much in depth code/modules are actually required for creating the NDEF records?  Do you think we could easily replace the Java server side code with Javascript or is that expecting too much?

**Comment by grundid** [comment]
The java applet does all the work by using the nfctools. Besides the applet one could drop the java backend.

**Comment by JohnMcLear** [comment]
So I guess question would be how intense would it to write(in javascript) the nfctools code that generates NDEF records?  I'm guessing it would be quite intensive?

**Comment by grundid** [comment]
From my point of view it does not make much sense to rewrite the NDEF encoding code in JavaScript. I also don't see why we should drop java in the back end. 
The idea of the project is to host it at ndefeditor.com and on this server java is not an issue. If you want to see new features at ndefeditor.com just create some pull requests and I'll update the web side.
